### ISSUE TITLE
MAPAS DE KARNAUGH

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-equipo-edwin#1]
[MAPAS DE KARNAUGH.pdf](https://github.com/user-attachments/files/18065082/MAPAS.DE.KARNAUGH.pdf)

**Comment by Ivan-PerezZ** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
